version: "2.15.1"

# tutorial from here , shoutout to bezkoder
# https://www.bezkoder.com/docker-compose-nodejs-mysql/
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    # env_file: .backend/.env
    # ports:
    #   - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # environment:
    #   # - DB_HOST=mysqldb
    #   - DB_USER=$MYSQLDB_USER
    #   - DB_PASSWORD=$MYSQLDB_PASSWORD
    #   - DB_NAME=$MYSQLDB_DATABASE
    #   - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  # frontend:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    env_file: ./backend/.env
    environment:
      MYSQL_USERNAME: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
# volumes:
